version: "3.7"

services:
    mariadb_inception:
        container_name: "mariadb"
        volumes:
          - mariadb_volume:/var/lib/mysql
        build: ./requirements/mariadb
        networks:
          - inception_network
        restart: always

    wordpress_inception:
        container_name: "wordpress"
        depends_on:
          - mariadb_inception
        volumes:
          - wordpress_volume:/var/www/wordpress
        build: ./requirements/wordpress
        networks:
          - inception_network
        restart: always

    nginx_inception:
        container_name: "nginx"
        depends_on:
          - wordpress_inception
        volumes:
          - wordpress_volume:/var/www/wordpress
        build: ./requirements/nginx
        networks:
          - inception_network
        ports:
        - 443
        restart: always

networks:
    inception_network:

volumes:
    mariadb_volume:
        driver: local
        driver_opts:
            o: bind
            type: none
            device: "/home/kbarbry/data/mariadb"
    wordpress_volume:
        driver: local
        driver_opts:
            o: bind
            type: none
            device: "/home/kbarbry/data/wordpress"